name: qemu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  TestRISCVVirtBoardQEMU:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Install Dependencies'
      run: sudo apt-get update && make ciprepare
    - name: 'Build oreboot image'
      run: |
        (
          cd src/mainboard/emulation/qemu-riscv
          make mainboard
          STACK_SIZES=$(make stack-sizes | tee /dev/stdout)
          if ! echo "$STACK_SIZES" | grep '0x[0-9a-f]\+\s\+[0-9]\+\s\+_start' > /dev/null; then
            echo "Error: Didn't see stack size of _start. make stack-sizes might be broken."
            exit 1
          fi
        )
    - name: 'Build QEMU'
      run: |
        sudo apt-get install qemu-system-misc
    - name: 'Run test'
      run: |
        (
          cd src/mainboard/emulation/qemu-riscv
          timeout 30s make run | tee serial
          grep "Running payload" serial
        )
